### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by angeiv** [hackerain/sphinxcontrib-excel-table#2]
Could not import extension sphinxcontrib.excel_table (exception: No module named 'excel_table')

```
localhost# python3
Python 3.6.5 (default, Aug 22 2018, 14:20:40)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphinxcontrib.excel_table
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/sphinxcontrib/excel_table/__init__.py", line 1, in <module>
    from excel_table import ExcelTable
ModuleNotFoundError: No module named 'excel_table'
```

**Comment by hackerain** [comment]
Already done: https://github.com/hackerain/sphinxcontrib-excel-table/commit/bc65543af2a819b163140ec3bf883b6dac4b34a4
